### PR TITLE
Added support for "not" comparison

### PR DESCRIPTION
**Pull request by chrilith**
Hi,

I needed a way to make a pseudo-"else" code inclusion/exclusion but with the current version of `gulp-remove-code` you have to define 2 different properties in order to achieve this.

This is why I created this pull request to allow "not" comparison.

It is quite easy:
- First we need to keep track of the value along side with the key
- Then I changed to regex so that we can optionally use `!`
- We can now handle replacement using a function to test if the `!` was defined

Voilà, you use the logical not perator and it doesn't affect existing implementations.

```javascript
//removeIf(production)
... some development code
//endRemoveIf(production)

//removeIf(!production)
... some production replacement code
//endRemoveIf(!production)
```

Hope you'll merge it!
Thank you and happy new year!
Chris

### CODE REVIEW

**Comment by crissdev** [comment]
Thanks @chrilith Can you add some tests to verify the functionality?

**Comment by chrilith** [comment]
Done!

One thing that haven't been specified I think: as the code is based on the options passed to the module, the comparison will be done on existing keys only!

If a key is not defined in the option, then, the test will not be performed at all.

For instance, with:
```json
{ "production": false }
```
The following:
```javascript
//removeIf(!production)
... some development code
//endRemoveIf(!production)

//removeIf(!message)
console.log("This is a message");
//endRemoveIf(!message)
```
will produce:
```javascript
//removeIf(!message)
console.log("This is a message");
//endRemoveIf(!message)
```

Because the key `message` is not present.

**Comment by crissdev** [comment]
> [...] the comparison will be done on existing keys only!
> If a key is not defined in the option, then, the test will not be performed at all.

I agree. In the future we might even log a warning in the console.

Thanks for this PR. 'going to merge this.

**Comment by chrilith** [comment]
Cool thanks!

**Comment by chrilith** [comment]
@crissdev, do you plan to release this change?

Thanks

**Comment by crissdev** [comment]
@chrilith yes. Before I publish the new version though, I want to make just a few more changes.

---
Please note you can install the current files from `master` branch using the following command.
```ssh
npm install git+ssh://git@github.com:crissdev/gulp-remove-code.git#bba3915b4700a578790256b20aca0126212f6537
```

**Comment by chrilith** [comment]
Ok cool, thanks.

**Pull request merged**
